name: Android CI

on:
  workflow_run:
    workflows: [ "Sonar Gradle Test" ]
    branches: [ main ]
    types:
      - completed
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
     # Allow tests to continue on other devices if they fail on one device.
      fail-fast: false
      matrix:
        api-level:
          - 21
          - 24
        
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew deploy
      
    - name: Install emulator
      run: ./setupEmulator.sh ${{ matrix.api-level }}
      
    - name: Do emulator
      run: ./runTest.sh

