name: Android CI

on:
  workflow_run:
    workflows: [ "Sonar Gradle Test" ]
    branches: [ main ]
    types:
      - completed
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        api-level: [19, 24, 30]
        
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew deploy
    - name: Run Test
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ matrix.api-level }}
        script: ./runTestAndroid.sh

